version: "3.2"

networks:
  uniting_net:


services:
  db:
    build:
      context: .
      dockerfile: deploy/db.Dockerfile
#    links:
#      - repeater
#      - proxy
    restart: always
    expose:
      - 5432
    networks:
      - uniting_net

  proxy:
    build:
      context: .
      dockerfile: deploy/proxy.Dockerfile
    ports:
      - 8192:8192
    restart: always
    networks:
      - uniting_net
    depends_on:
      - db
    command:
      /bin/sh -c "go run cmd/proxy/main.go ./proxy_config.json"
    volumes:
      - ./:/home/app

  repeater:
    build:
      context: .
      dockerfile: deploy/repeater.Dockerfile
    ports:
      - 8193:8193
    networks:
      - uniting_net
    restart: always
    depends_on:
      - db
    command:
      /bin/sh -c "go run ./cmd/repeater/main.go ./repeater_config.json"

